### ISSUE TITLE
Frost Throw Damage

### ISSUE THREAD

**Issue by xJayohJay** [ermaccer/ultimate-mkd#7]
First part of Frost's throw hits twice causing 18% instead of 13% damage

Hopefully is an easy fix but if not I wouldn't really worry about it 😅

**Comment by ermaccer** [comment]
While it's probably a bug for Frost (considering how two 5% hits happen immediately), some characters actually have more than 13% of throw damage like Ashrah, will be fixed after Goro is ported.
