### ISSUE TITLE
Widescreen problem

### ISSUE THREAD

**Issue by wangnukem** [ermaccer/ultimate-mkd#9]
First of all, thanks for the great mod!

I'm playing UMKD in Pcsx2 emulator and it doesn't load widescreen patches. When I boot up unmodded, original MKD, it loads widescreen patches.

How can I enable widescreen patch while using Ultimate MKD?
(P.S. : I know game has a widecreen option in menus, but it's skewed)

**Comment by ermaccer** [comment]
If you're using the PS2 version for a PS2 compatible ISO you can't do much here, PCSX2 calculates CRC of the main executable and that gets changed with each version so you will have to manually update everything to match modded CRC. If you're emulating on PC just use the fork/custom version, that way executable stays the same (CRC too) and any patches will work without problems.

How is it skewed? It's a correct implementation.
